export const characters = [
  {
    name: "Luke Skywalker",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Brown",
    eyes: "Blue",
    height: "172 cm",
    origin: "Tatooine",
    affiliation: "Jedi Order",
    image:
      "https://i.pinimg.com/736x/a0/be/7f/a0be7f4d404e4a6855d8e9200b96bcb4.jpg",
  },
  {
    name: "Han Solo",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Brown",
    eyes: "Brown",
    height: "180 cm",
    origin: "Corellia",
    affiliation: "Rebel Alliance",
    image: "https://images3.alphacoders.com/865/86515.jpg",
  },
  {
    name: "Leia Organa",
    race: "Human",
    species: "Human",
    gender: "Female",
    hair: "Brown",
    eyes: "Brown",
    height: "150 cm",
    origin: "Alderaan",
    affiliation: "Rebel Alliance",
    image:
      "https://media.vogue.es/photos/5cc76215a6e11735f454dcb1/master/w_1600%2Cc_limit/princesa_leia_383.jpg",
  },
  {
    name: "C-3PO",
    race: "Droid",
    species: "Droid",
    gender: "N/A",
    hair: "N/A",
    eyes: "Yellow",
    height: "167 cm",
    origin: "Tatooine",
    affiliation: "Jedi Order",
    image:
      "https://cdnb.artstation.com/p/assets/images/images/048/084/873/large/pierre-yves-real-c3p0.jpg",
  },
  {
    name: "R2-D2",
    race: "Droid",
    species: "Droid",
    gender: "N/A",
    hair: "N/A",
    eyes: "Red",
    height: "96 cm",
    origin: "Naboo",
    affiliation: "Jedi Order",
    image:
      "https://www.hollywoodreporter.com/wp-content/uploads/2017/06/r2-d2.jpg?w=1296",
  },
  {
    name: "Darth Vader",
    race: "Human",
    species: "Human Cyborg",
    gender: "Male",
    hair: "N/A",
    eyes: "Yellow",
    height: "202 cm",
    origin: "Tatooine",
    affiliation: "Galactic Empire",
    image: "https://wallpapercave.com/wp/wp11252440.jpg",
  },
  {
    name: "Obi-Wan Kenobi",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Brown",
    eyes: "Blue",
    height: "182 cm",
    origin: "Stewjon",
    affiliation: "Jedi Order",
    image:
      "https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/08/hipertextual-se-confirma-serie-obi-wan-kenobi-con-ewan-mcgregor-disney-2019892534-scaled.jpg?fit=2560%2C1707&quality=55&strip=all&ssl=1",
  },
  {
    name: "Yoda",
    race: "Unknown",
    species: "Unknown",
    gender: "Male",
    hair: "White",
    eyes: "Brown",
    height: "66 cm",
    origin: "Unknown",
    affiliation: "Jedi Order",
    image:
      "https://c4.wallpaperflare.com/wallpaper/865/687/666/star-wars-yoda-jedi-wallpaper-preview.jpg",
  },
  {
    name: "Boba Fett",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Black",
    eyes: "Brown",
    height: "183 cm",
    origin: "Kamino",
    affiliation: "Galactic Empire",
    image: "https://cdn.zendalibros.com/wp-content/uploads/serie-boba-fett.jpg",
  },
  {
    name: "Lando Calrissian",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Black",
    eyes: "Brown",
    height: "177 cm",
    origin: "Socorro",
    affiliation: "Rebel Alliance",
    image:
      "https://img.europapress.es/fotoweb/fotonoticia_20180710095949_1200.jpg",
  },
  {
    name: "Padmé Amidala",
    race: "Human",
    species: "Human",
    gender: "Female",
    hair: "Brown",
    eyes: "Brown",
    height: "165 cm",
    origin: "Naboo",
    affiliation: "Galactic Republic",
    image:
      "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2022/10/natalie-portman-2833953.jpg?itok=InMCjWLM",
  },
  {
    name: "Mace Windu",
    race: "Human",
    species: "Human",
    gender: "Male",
    hair: "Grey",
    eyes: "Brown",
    height: "188 cm",
    origin: "Haruun Kal",
    affiliation: "Jedi Order",
    image:
      "http://4.bp.blogspot.com/-82gM5fQxnfc/VXHA007veUI/AAAAAAAAC1c/UeH3Ipu4L30/s640/53035.jpg",
  },
];
